### ISSUE TITLE
Upgrade to Rails 4.1.x & Devise

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#140]
After I upgraded the i18n gem to 0.6.11, we are getting the following deprecated warning when we run the rspec tests:
 * [DEPRECATED] I18n's :recue_format option will be removed from a future release. All exception messages will be plain text. If you need the exception handler to return an html format please set or pass a custom exception handler.
 * We did not get it for i18n gem 0.6.9.

**Comment by jasnow** [comment]
@cktricky - Can we make this issue's title 'Adding Devise to Railsgoat' or create another one for Devise work?

**Comment by cktricky** [comment]
Yes, lets do that, lets switch to Devise and let the "Auth from scratch" examples live in the Rails 3.x branch/tutorials. Do you want to open it?

**Comment by cktricky** [comment]
Oh and we can close this issue
