### ISSUE TITLE
Creating a user in empty database fails

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#179]
This commit (4e6006dcc88049a3fbcb45bc6ed96d74371b3f41) tries to create the auth_token during User creation, but in an empty database, the assign_user_id method won't do anything - I think.

I've changed the README (in a coming PR) to show with mysql that `db:setup` should be used instead of `db:create` and `db:migrate` because the latter won't execute `seeds.rb`, leaving the db empty. 

Be good to fix the bug - probably in `assign_user_id` - 0d84112 - to make sure at least 1 is assigned.

**Comment by cktricky** [comment]
Understood, yes their was some level of assumption that folks would seed the db, oops! Seems like a no-brainer in retrospect.

**Comment by cktricky** [comment]
Also, I just realized what you meant w/ regards to the README. The first example shows `db:setup` but when we talk about mysql we demonstrate using `rake db:create db:migrate`, instead. Are you tackling this in the PR or should I assign myself?

**Comment by chrismo** [comment]
You can do it - I'm going through the exercises again for my annualish review of these items. I may pick up some other tweaks and submit them all at once - I dunno - but I don't know if I'll get to stay heads down on this enough this week :)

**Comment by cktricky** [comment]
Ha! Luckily I'm dedicating some time to a "refresh" of this platform over the next few weeks. Appreciate your efforts on this btw!

**Comment by chrismo** [comment]
I ran across this again today, and a related problem in UserFixture and had to fix both to continue:

```
From b320f779adb6bb036708b556e62c0a97a9417774 Mon Sep 17 00:00:00 2001
From: chrismo <chrismo@clabs.org>
Date: Tue, 6 Jan 2015 11:47:05 -0600
Subject: [PATCH] assign_user_id and UserFixture password fixes.

When the database is empty, which can happen in the test database and in
the dev database if the seeds.rb aren't applied, the assign_user_id
method would not assign an id and the newer before_filter block to
generate_token would fail.

UserFixture had a password on it that wouldn't pass the new validation
rules once that vulnerability is patched.
---
 app/models/user.rb           | 6 +++++-
 spec/support/user_fixture.rb | 6 +++---
 2 files changed, 8 insertions(+), 4 deletions(-)

diff --git a/app/models/user.rb b/app/models/user.rb
index 9c5cc7f..21b4fd1 100755
--- a/app/models/user.rb
+++ b/app/models/user.rb
@@ -77,7 +77,11 @@ class User < ActiveRecord::Base
   def assign_user_id
     unless @skip_user_id_assign.present? || self.user_id.present?
       user = User.order("user_id").last
-      uid = user.user_id.to_i + 1 if user && user.user_id && !(User.exists?(:user_id => "#{user.user_id.to_i + 1}"))
+      uid = if user && user.user_id && !(User.exists?(:user_id => "#{user.user_id.to_i + 1}"))
+              user.user_id.to_i + 1
+            else
+              1
+            end
       self.user_id = uid.to_s if uid
     end
   end
diff --git a/spec/support/user_fixture.rb b/spec/support/user_fixture.rb
index 8a5f182..bb71be2 100644
--- a/spec/support/user_fixture.rb
+++ b/spec/support/user_fixture.rb
@@ -5,14 +5,14 @@ class UserFixture
   end
 
   def self.normal_user
-    password = 'aoeuaoeu'
+    password = 'thi$ 1s cOmplExEr'
     user = User.new(:first_name => 'Joe', :last_name => 'Schmoe',
                     :email => 'joe@schmoe.com', :password => password, :password_confirmation => password)
     def user.clear_password
-      'aoeuaoeu'
+      'thi$ 1s cOmplExEr'
     end
     user.build_benefits_data
     user.save!
     user
   end
-end
\ No newline at end of file
+end
-- 
1.8.4

```

**Comment by chrismo** [comment]
If you save all of that to file.patch, should be able to apply with `git am < file.patch`

**Comment by cktricky** [comment]
Done in 73e8ab972b29a716e0f87cb053f99b058a01b2bf. Thanks again! Also, I think I'll end up putting up a flash notification that you need to seed the data if the db shows empty (since we want folks to seed so that they can correctly utilize the application for training).
