### ISSUE TITLE
SSN display vuln has no spec

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#182]
This is probably on me, as this was in there the first time around. I think it should be simple to add, though I may not have time this time around :/

**Comment by chrismo** [comment]
actually, there is one ... hmmm: https://github.com/OWASP/railsgoat/blob/master/spec/vulnerabilities/sensitive_data_exposure.rb#L12

**Comment by cktricky** [comment]
Fair to close the issue then?

**Comment by chrismo** [comment]
ok - closing this, I'm not sure why the spec wasn't going to pending when I was expecting it to, but I guess after fixing other things it went pending with the rest of them.
