### ISSUE TITLE
Why are solutions inlined in the code, commented out?

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#184]
I think I'd prefer all of the solution code not be left in the sources remmed out, esp. since solutions are included in the tutorial. Having the commented out solutions thwarts attempts by a dev wanting to try and figure these things out (personally, I learn better if I have to solve it, rather than 'cheat'). 

I'm fine with the solution options in the tutorial, as this gives someone wanting to quickly browse example code and solutions without fixing anything.

I think removing the commented out solutions will help serve the dev who wants to dig in, while the casual dev just looking for info can go through the tutorials.

My 3 cents ;)  Thoughts?

**Comment by cktricky** [comment]
Let's remove it in the 4.x branch and see what ppl say. Seem fair?

**Comment by chrismo** [comment]
All of the code related to encrypting SSNs is possibly a good example of leaving the solution code in the source. It's a fair amount of work and just starting with nothing may not be that helpful. Dunno.

**Comment by cktricky** [comment]
Maybe we draw the line at this - If it can be put into a code snippet
(meaning succinct and not overly complex), it does *not* have a commented
out code snippet to go with. If it is more involved and a fix cannot be
easily placed into code snippets, it stays in the code and we reference it
in the tutorials.

**Comment by chrismo** [comment]
I've had vague thoughts of moving all solutions into monkey-patching modules such that they're out of the way, but then could be mixed in by requiring some sort of solutions path ... you could even shoot for the moon and attempt to auto-render that code into the tutorial pages - so when that code changes, the tutorial is automatically up-to-date. but ... that probably feels like more work than I'm willing to do :)

**Comment by cktricky** [comment]
I like this. Ya - I'm actually wanting us to go a more complex, more
involved route. Not from the user experience perspective obviously, more
engineering overhead to improve the experience. Timely given that I'm
working through a new tutorial process in the *tuts* branch as time
permits.

**Comment by chrismo** [comment]
(recording for completeness) - the bcrypt solution code only appears in the tutorial, looks like.

**Comment by chrismo** [comment]
Another pro for being able to automatically switch in monkey-patching solution code is the build automation can make sure all of the specs DO go to pending when solutions are in place -- I found a few places where vuln solutions broke the specs due to changing code since the specs were written.

**Comment by ajvb** [comment]
:+1: To this. I was really bummed when I was going to try and fix a vulnerability and discovered the solution commented out.

**Comment by cktricky** [comment]
We'll remove them, thank you.

-- 
Ken Johnson, CTO
nVisium
775.233.8383 Mobile
*ken@nvisium.com* <ken@nvisium.com>
https://nvisium.com

Inc. 500 list of America’s fastest-growing private companies
