### ISSUE TITLE
undefined method `iv` for nil:NilClass

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#185]
While working through fixing the goat, I fixed the work_info view to show last_four, but hadn't dug into any of the other encryption related stuff, and no users had any key_management records, which led to a confusing error `undefined method`iv' for nil:NilClass` pointing at this raise line:

```
  def iv
    raise "No IV for this User" if !(self.key_management.iv)
    self.key_management.iv
  end
```

So ... I think maybe adding another check for the presence of self.key_management along with some comments perhaps pointing the way to all of the solution code in `/tutorials/exposure`. 

(Also, this check for vi being nil in encrypt and decrypt isn't necessary since the `iv` method will raise if it is):

```
    aes.iv = iv if iv != nil
```

---

On a related note, this is an interesting example for #184 - to not include solution code in the source, just in the tutorial - in this case, adding in SSN encryption is a fair amount of work. And some of this is already in place, but not remmed out, though the seeds enhancement is remmed out ... so ... I don't have any easy answer here for the best user experience, just thinking out loud. :/

**Comment by cktricky** [comment]
Ahh, I actually had seen this before and forgot to make an issue for it.
Thanks!
