### ISSUE TITLE
ApplicationController fix to check paid_time_off first

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#187]
I ran into this in the middle of fixing the site, not exactly sure of the circumstances, but obviously something to do with missing user data ... simple fix:
-      if !(current_user.retirement || current_user.paid_time_off.schedule || current_user.paid_time_off || current_user.work_info || current_user.performance)  
-      if !(current_user.retirement || current_user.paid_time_off || current_user.paid_time_off.schedule || current_user.work_info || current_user.performance)

Without this change, it'll raise a nil exception on paid_time_off trying to check the paid_time_off.schedule prior to checking the paid_time_off itself.

**Comment by cktricky** [comment]
Good call 👍
