### ISSUE TITLE
Fix for redirect vuln could go one step further to solve unvalidated_redirects_spec.rb breakage

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#188]
As is, the line to shave off different domains in the redirect `path = URI.parse(params[:url]).path if params[:url].present?` can still lead to an invalid route, and in fact the `unvalidated_redirects_spec.rb` will blow up on an exception rather than just go to pending when this fix is in place. Adding a check on the route can save that problem as well:

```
    path = home_dashboard_index_path
    begin
      path = URI.parse(params[:url]).path if params[:url].present?
      Rails.application.routes.recognize_path(path) # raises if invalid
    rescue
      path = home_dashboard_index_path
    end
```

**Comment by cktricky** [comment]
Closing this as #228 has more info on the same issue.
