### ISSUE TITLE
If UsersController doesn't reject admin param, then just removing admin from mass assignment causes specs to raise exception

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#189]
`+   user = User.new(params[:user].reject { |k| 'admin' == k })`

Changing that line will allow the spec to go to pending when the mass assignment change is made in User. Otherwise the spec is broken.

**Comment by jmmastey** [comment]
I think this is no longer a relevant concern since changing to a `attr_accessible` / strong params strategy. @chrismo could you confirm?

**Comment by jmmastey** [comment]
@cktricky I dug around in this a bit more and I'm pretty positive it's no longer relevant since we moved off of attr_accessible. I think we can safely close this. What do you think?

**Comment by cktricky** [comment]
Thanks @jmmastey I'll close it!
