### ISSUE TITLE
allow_forgery_protection config change in test.rb required to get spec to go pending

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#190]
This is only set to false in the test.rb file, but I had to hunt it down to get the spec to go to pending after doing the rest of the fixes as shown in the tutorial solution for CSRF.

Maybe test.rb should just be changed to this?

`+  config.action_controller.allow_forgery_protection    = true`

**Comment by cktricky** [comment]
Done in 907045488d404bb6f608b1757279fef31e9485c6 thanks!

**Comment by chrismo** [comment]
No problem! :) Thx for the maintainence work :) I couldn't decide if that should just be changed or called out in the tutorial.

**Comment by cktricky** [comment]
Good catch, I'm hoping these types of things will be detected as more folks
use the unit-tests. Linking tutorials with their unit-tests and annotating
that there are unit-tests should draw more feedback/usage (I hope).

On Fri, Jan 9, 2015 at 11:43 AM, chris morris <notifications@github.com>
wrote:

> No problem! :) Thx for the maintainence work :) I couldn't decide if that
> should just be changed or called out in the tutorial.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OWASP/railsgoat/issues/190#issuecomment-69360838>.
>



-- 
Ken Johnson, CTO
nVisium
(775) 233-8383

*ken.johnson@nvisium.com
<http://ken.johnson@nvisiumsecurity.com/>https://www.nvisium.com
<https://www.nvisium.com/>*
