### ISSUE TITLE
All of the passwords in seeds and specs don't pass fixed validation rules

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#191]
Most if not all of the specs fail once the new password validation rules are put into place, because the seeds.rb have invalid passwords according to the new rules.

I don't know if hardcoding seeds.rb passwords to pass the new rules will allow the John the Ripper attack mentioned in the tutorial to work.

sql_injection_spec also has a hardcoded password that needs to be modified to obey the new rules.

**Comment by cktricky** [comment]
Might make sense to just detect the failure during seeds file population, then revert to a stronger password for each account being created. Dunno. Thinking it through.

**Comment by jmmastey** [comment]
Can I push up a quick branch for this? It caused lots of confusion with my students when they fixed the password complexity issue and then the seed file just stopped working. Considering the seedfile, for instance, isn't actually a lesson, it's hard to hunt down all the places where the test data causes issues.

In some cases, the bad passwords caused a failing spec to become pending, and/or a pending spec to become failing again. This was a big speedbump for learning.

Here's where I see problems:
* In `db/seeds.rb`, all users have noncompliant passwords.
* In `spec/vulnerabilities/password_hashing_spec.rb`, there's an unsafe password and it's not clear to students why the user record won't save, etc. This is separate from `password_complexity_spec.rb`.
* In `spec/vulnerabilities/sql_injection_spec.rb`, as @chrismo mentioned.

**Comment by cktricky** [comment]
Ahh, I think we'd need to add a `user.save(:validate => false)` in the seeds file. Would that help?

**Comment by jmmastey** [comment]
Any reason why we couldn't just change to conformant passwords in the seeds? The user will still hit the  `password_complexity_spec` successfully. Or, honestly, I think there's really only one or two of those seeds (I think the admin, specifically) that other activities rely on.
