### ISSUE TITLE
[design] New Logo for Project

### ISSUE THREAD

**Issue by Nevraeka** [OWASP/railsgoat#193]
Any thoughts on this? 
![railsgoat](https://cloud.githubusercontent.com/assets/647043/5801026/45ad3494-9fb4-11e4-9765-36fa4c6a06f0.png)

**Comment by cktricky** [comment]
Love it, this is awesome. We should use it!

On Mon, Jan 19, 2015 at 8:22 AM, Erik Isaksen <notifications@github.com>
wrote:

> Any thoughts on this?
> [image: railsgoat]
> <https://cloud.githubusercontent.com/assets/647043/5801026/45ad3494-9fb4-11e4-9765-36fa4c6a06f0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OWASP/railsgoat/issues/193>.
>



-- 
Ken Johnson, CTO
nVisium
(775) 233-8383

*ken.johnson@nvisium.com
<http://ken.johnson@nvisiumsecurity.com/>https://www.nvisium.com
<https://www.nvisium.com/>*

**Comment by Nevraeka** [comment]
Any tweaks? Or constructive criticism? I'll upload an .eps & new .png when its finalized

**Comment by cktricky** [comment]
You know, I really don't have anything to add, it looks pretty cool. 

@meowris (our designer), do you have any thoughts? This is a logo for Railsgoat.

**Comment by Nevraeka** [comment]
I sent the various formats to your emails @cktricky @mccabe615 . Here is the final logo

![railsgoat-hr](https://cloud.githubusercontent.com/assets/647043/5816826/f41d4208-a072-11e4-83e9-199e46305b7b.png)
