### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by cktricky** [OWASP/railsgoat#194]
It has been asked that our tutorial also be made available in wiki form.

I'd like to implement a solution so that these can be managed from on centralized repo versus maintaing both a wiki and the railsgoat code base. Something to think about for the tuts branch (tutorial overhaul)

**Comment by jasnow** [comment]
Have you thought of using Github's wiki feature for this. Here is the wiki for a project I worked on: https://github.com/PeaceCorps/medlink/wiki

**Comment by cktricky** [comment]
I'm done porting the initial content that was in railsgoat to the wiki. Next, I'll submit a PR that has these tutorials removed from within the app (no sense in maintaining in two places).

**Comment by cktricky** [comment]
https://github.com/OWASP/railsgoat/pull/197

**Comment by jasnow** [comment]
Suggestions:
 * Change the ["a1", filenames to "a1-Injections", "a2" to "a2-Broken Authentication and Session Management", etc] in the right sidebar to match the TOC page.
 * Note the the sidebar sorts the entries so "a10" comes before "a2."

**Comment by cktricky** [comment]
I've done a bit of that after getting your suggestion but I have to say - the wiki pages listing is terrible because I can't actually organize this into sub-directories. Or at least I've not found a way.

**Comment by cktricky** [comment]
#a6e5ba63ccf57449a836e91ae96ddff95aa63f73 Fixes this
