### ISSUE TITLE
Ruby Version is out of date in Gemfile

### ISSUE THREAD

**Issue by cktricky** [OWASP/railsgoat#201]
Since the ruby version is out of date, the Dockerfile exits with errors during the build process.

**Comment by mccabe615** [comment]
@cktricky Is this still true? We're running the latest version of Ruby and the docker images builds. 

https://hub.docker.com/r/mccabe615/railsgoat/builds/bgbnr9sp5j6cyb4pym6bsjd/

**Comment by cktricky** [comment]
Seems to come up fine now. I'd try running `vagrant up` to make sure this still works as expected but in terms of just the docker image, it seems to be coming up fine.
