### ISSUE TITLE
Convert rspec 2.99 to 3.0.x including the changed "pending" role in Railsgoat project.

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#225]
Convert rspec 2.99 to 3.0.x including the changed "pending" role in Railsgoat project.

Separated #159 into 2 issues.

**Comment by cktricky** [comment]
So pull request #226 is part of the effort to upgrade to 3.0 @jasnow ?

**Comment by jasnow** [comment]
prereq

**Comment by cktricky** [comment]
Thank you!

**Comment by jasnow** [comment]
You are welcome.
