### ISSUE TITLE
DOM XSS does not work with Firefox version 40 or above

### ISSUE THREAD

**Issue by jx6f** [OWASP/railsgoat#229]
I found that "A3 Cross Site Scripting DOM Based" does not work with Firefox version 40 or above.

https://github.com/OWASP/railsgoat/wiki/A3-Cross-Site-Scripting-DOM-Based#dom-based-cross-site-scripting-attack

According to this Firefox's specification change, `location.hash` returns percent-encoded value.

https://www.fxsitecompat.com/en-CA/docs/2015/urlutils-hash-no-longer-decodes-fragment/

* Firefox 39.0.3

```
> location.hash
"#test=<script>alert(1)</script>"
```

* Firefox 40.0

```
> location.hash
"#test=%3Cscript%3Ealert(1)%3C/script%3E"
```

How about to add decodeURIComponent to app/views/sessions/new.html.erb ?
```
       var hashParam = location.hash.split("#")[1];
       var paramName = hashParam.split('=')[0];
       var paramValue = hashParam.split('=')[1];
+      paramValue = decodeURIComponent( paramValue );
       document.write("<OPTION value=3>" + paramValue + "</OPTION>");
     } catch(err) {
     }
```

**Comment by cktricky** [comment]
Resolved using the method you demonstrated @jx6f , thank you. Found in commit fafe94b571fcb064a719ccdb0a0412bb2493bd0c
