### ISSUE TITLE
Empty Railsgoat Wiki pages

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#247]
This maybe to known but ran into these empty wiki pages today.
- "A5 - Security Misconfiguration"
  - https://github.com/owasp/railsgoat/wiki/R4-A5-Security-Misconfiguration
- "Extras - Logic Flaws" (redirects back to https://github.com/OWASP/railsgoat/wiki page)
  - https://github.com/owasp/railsgoat/wiki/extras-logic-flaws
- "Extras - Metaprogramming" (redirects back to https://github.com/OWASP/railsgoat/wiki page)
  - https://github.com/owasp/railsgoat/wiki/extras-metaprogramming

**Comment by cktricky** [comment]
Ouch, ya, this is part of me changing the tutorials up and I introduced some issues. I'll clean this up later.

**Comment by mccabe615** [comment]
I _think_ I fixed this. I added some blank pages for placeholders then updated links to pages that already existed. @jasnow let me know if there are other ones.

**Comment by jasnow** [comment]
I still see the same behavior as on June 22.

**Comment by jasnow** [comment]
Update on status of 3 wiki links.

......................................................................
Rails 3

 * A5 - Security Misconfiguation (2 sublinks worked)

 * Extras - Logic Flaw => 2 sublinks which go back to home wiki (open)

 * Extras - Metaprogramming => 3 sublinks =>
   * Metaprogramming (ok)
   * Ruby Metaprogramming (Got Heroku error, open)
   * Contstantize (went back to home wiki, open)

......................................................................
Rails 4

 * A5 - Security Misconfiguation - Blank (open)

 * Extras - Logic Flaw - Blank (open)

 * Extras - Metaprogramming - Blank (open)
EOF

**Comment by cktricky** [comment]
Taking as stab at this... will update this as progress is made:

A5 - Security Misconfiguation - Blank (open) 🐛 
~Extras - Logic Flaw - Blank (open)~ ✅ 
Extras - Metaprogramming - Blank (open) 🐛 
EOF

**Comment by cktricky** [comment]
Closing as I believe this is now resolved
