### ISSUE TITLE
Update readme re:phantonjs

### ISSUE THREAD

**Issue by mccabe615** [OWASP/railsgoat#252]
@jasnow can you update the readme with the pertinent info for phantomjs? If we need a certain version of phantomjs than that should be documented. Thanks for this PR!

**Comment by jasnow** [comment]
@mccabe615 - Added phrase containing version to README as part of PR#253. Would appreciate if you would review and comment. Thanks.

**Comment by cktricky** [comment]
Looks like this was done already in #253
