### ISSUE TITLE
Error running tests for the first time

### ISSUE THREAD

**Issue by wobh** [OWASP/railsgoat#258]
With a clean install, I run into this error when running tests:

```
~/opt/src/railsgoat$ bundle exec rake test
rake aborted!
LoadError: cannot load such file -- rails/performance_test_help
/home/me/opt/src/railsgoat/.direnv/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/me/opt/src/railsgoat/.direnv/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/home/me/opt/src/railsgoat/.direnv/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/me/opt/src/railsgoat/.direnv/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/me/opt/src/railsgoat/test/performance/browsing_test.rb:2:in `<top (required)>'
...
```

I was able to get past this error by adding gems `rails-perftest` and `ruby-prof`. (https://github.com/rails/rails-perftest). However, there's another error after this one:

```
$GEM_HOME/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:46:in `print': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	from $GEM_HOME/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance/ruby.rb:54:in `block (2 levels) in record'
...
```

This has me wondering if the performance tests are worth keeping, or perhaps they should be tagged in someway so they aren't run in Rails 4, for now.

**Comment by cktricky** [comment]
For some reason I never saw this issue opened until today while going in and trying to do clean-up. So sorry @wobh but did you find your answer?

**Comment by cktricky** [comment]
@wobh Poking one more time before closing, thanks!

**Comment by wobh** [comment]
Sorry! I did not find an answer. I became rather busy with other things and forgot all about it. I'll circle back to this soon, I hope.

**Comment by zactly-ken** [comment]
I'm the one who is sorry 😄 (as I missed this issue for nearly 2 months). Thank you!

**Comment by cktricky** [comment]
I'm the one who is sorry 😄 (as I missed this issue for nearly 2 months). Thank you!

**Comment by jasnow** [comment]
@cktricky - Was able to reproduce by "bundle exec rake test".
Note that "test/performance/browsing_test.rb" is not run by default. 
Should we remove it or fix the repo to run it cleanly?

**Comment by cktricky** [comment]
Hey @jasnow I'm trying to see if I can just fix it. Mainly in the case someone decided they wanted to use this functionality in the future - figured it'd make sense to try and get it working rather than removing. Consider it "In progress".

**Comment by cktricky** [comment]
@wobh and @jasnow I've resolved this issue on both the Rails 4 and 5 branches. Thanks for your help!
