### ISSUE TITLE
Run Rubocop *and cry*

### ISSUE THREAD

**Issue by cktricky** [OWASP/railsgoat#264]
As @mccabe615 pointed out, we should really run a linter/rubocop against the railsgoat code-base (no, not so we can cry) - so that we can make this all look a little more professional.

**Comment by oreoshake** [comment]
Personally I'm not a fan of the default rubocop settings and use https://github.com/github/rubocop-github as a starting point. Unfortunately, it can lag behind in supported rubocop version.

`rubocop -a && git commit -am "yolo" && git push origin HEAD`

**Comment by cktricky** [comment]
Oooh, ty kindly sir. 🙇  We'll go this route. (it won't be a small effort, I'm sure)

**Comment by cktricky** [comment]
We now have [this pull request merged](https://github.com/OWASP/railsgoat/pull/286) which is basically step 1 and this issue, step 2.
