### ISSUE TITLE
Update RailsGoat to OWASP Top Ten 2017 version

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#305]
* Update RailsGoat to OWASP Top Ten 2017 version.
   * Found this in README file: Conversion to the OWASP Top Ten 2013 completed in November, 2013.

* Reference: https://www.owasp.org/index.php/Top_10-2017_Top_10

 * Reference: https://github.com/OWASP/Top10

 * OWASP Slack channel: [project-top-10 (documentation)](https://owasp.slack.com/messages/C1QBMGU69)

**Comment by jasnow** [comment]
Is OWASP Top 10 - 2017 version official?

**Comment by jasnow** [comment]
**shaddygarg [Today at 8:50 AM] in #project-railsgoat**
Hey, I was working on the proposal for the OWASP top ten project but I am unsure about some points. What does the project OWASP top ten exactly include?? I read the relevant issue and It mentions that support needs to be added for the 2017 version and back support for the 2010 version!! How is one supposed to start doing this?? I plan to open a WIP request and build upon that in the coming GSoC. Can you point out some relevant links??

**Al [20 minutes ago]**
(1) What does the project OWASP top ten exactly include??
   -- Have you googled "OWASP Top 10 2017" or "OWASP Top 10 2013 2017"?
(2) How is one supposed to start doing this (backport to 2010)?
   -- Yes, what are the different approaches to do that?
(3) Can you point out some relevant links??"
   -- What do you have now?
   -- Also OWASP's #project-top-10 channel can be a resource.
   -- You can also post questions to the OWASP Google Group and
      #project-railsgoat Slack channel.

**shaddygarg [14 minutes ago]**
Sorry for being very vague in my question. Yes, I have read about the top ten and most of the vulnerabilities are the same for 2010, 2013 and 2017. So, what exactly is meant by adding the support. Does this mean that the new vulnerabilities that were included in 2017 need to be added into the railsgoat project. For the backsupport to 2010, vulnerabilities were merged into 2013. So, what exactly needs to be done for 2010? (edited)

**shaddygarg [14 minutes ago]**
I have joined the #project-top-10 channel and the two pdfs are what I am refering : 
1. https://www.owasp.org/images/f/f8/OWASP_Top_10_-_2013.pdf
2. https://www.owasp.org/images/b/b0/OWASP_Top_10_2017_RC2_Final.pdf (edited)

**Comment by jasnow** [comment]
**shaddygarg [9:02 AM]**
uploaded and commented on this image: [OWASP.PNG](https://owasp.slack.com/files/U995JPMAL/F9RTPDG9K/capture.png)

The vulnerabilities A7, A9, A8 are merged into some other vulnerabilities of 2013 and other vulnerabilities are the same. 
Source: https://www.owasp.org/images/f/f8/OWASP_Top_10_-_2013.pdf

**Al [9:06 AM]**
"2010 and 2013 support after adding 2017 support" - I have not thought thru this but the idea is not to lose the vulnerabilities that were removed from 2010 and 2013. There is probably multiple ways to support ("no lose the information"/source code) for these old vulnerabilities.

**Comment by jasnow** [comment]
@shaddygarg -- Where would you find the RailsGoat supporting 2010 vulnerabilities?

**Comment by shaddygarg** [comment]
@jasnow -- I am currently researching for the differences between the 2010 and 2017 vulnerabilities so that for adding the 2017 vulnerabilities, I can have a better perspective of developing the vulnerabilities in such a way that they don't interfere. This way we can both preserve the vulnerabilities of 2017 along with 2013 and 2010.

**Comment by cktricky** [comment]
Why would we want to maintain 2010/2913 support? Typically we just upgrade master to whatever the current owasp top 10 list is. We are more concerned with Rails versions (ie - 3,4, and 5) when it comes to historical context. The OWASP Top 10 is just “whatever the latest list is”.

**Comment by jasnow** [comment]
```
Why would we want to maintain 2010/2013 support?
```
@cktricky -  you want just the latest, I will change my description.

**Comment by cktricky** [comment]
I don’t know because I am not sure about the story/context behind it, that’s why I’m asking :smile:. Know what we typically do but wasn’t sure if this was for some larger effort that was part of GSoC and I was unaware of.

**Comment by jasnow** [comment]
@shaddygarg - FYI: Note that this GitHub idea issue has been changed to only cover the 2017 vulnerabilities.

**Comment by jasnow** [comment]
Spring Cleaning
