### ISSUE TITLE
Add documentation on "How to Upgrade" RailsGoat

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#335]
Provide steps in the documentation to "How to Upgrade" this repo.

🐞 **Problem**

Currently unclear exactly how to upgrade this repo.

🎯 **Goal**

To be clear on how to upgrade this repo.

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by jasnow** [comment]
Unclear if this is needed so closing this issue.

**Comment by cktricky** [comment]
Left a question re: these issues being closed here: https://owasp.slack.com/archives/C04THC44W/p1524771400000710
