### ISSUE TITLE
Add rjs vulnerability?

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#72]
http://homakov.blogspot.com/2013/11/rjs-leaking-vulnerability-in-multiple.html

**Comment by mccabe615** [comment]
I don't think RJS is in use much anymore. @cktricky what do you think about closing?

**Comment by jasnow** [comment]
Do we know the percentages of each version of Rails used in production?

**Comment by cktricky** [comment]
I don't have any stats, no.

**Comment by cktricky** [comment]
also - I'm okay to close it @mccabe615

**Comment by mccabe615** [comment]
![screen shot 2016-09-06 at 12 16 18 pm](https://cloud.githubusercontent.com/assets/1463253/18281670/ba19e9ba-742b-11e6-88c5-25a88aaa0f87.png)

Doesn't show total downloads but clearly Rails 4 is growing, from here. 

https://infinum.co/the-capsized-eight/articles/analyzing-rubygems-stats-v2015

**Comment by mccabe615** [comment]
Closing it out.

**Comment by cktricky** [comment]
I think I got just mic dropped on  😂
